# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lazystudent',
                'doc_host': 'https://frankausberlin.github.io',
                'git_url': 'https://github.com/frankausberlin/lazystudent',
                'lib_path': 'lazystudent'},
  'syms': {'lazystudent.core': {'lazystudent.core.foo': ('yamler.html#foo', 'lazystudent/core.py')}}}
