# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lazystudent',
                'doc_host': 'https://frankausberlin.github.io',
                'git_url': 'https://github.com/frankausberlin/lazystudent',
                'lib_path': 'lazystudent'},
  'syms': { 'lazystudent.core': { 'lazystudent.core.Yamler': ('yamler.html#yamler', 'lazystudent/core.py'),
                                  'lazystudent.core.Yamler.__init__': ('yamler.html#yamler.__init__', 'lazystudent/core.py'),
                                  'lazystudent.core.Yamler.activate': ('yamler.html#yamler.activate', 'lazystudent/core.py'),
                                  'lazystudent.core.Yamler.dictcopy': ('yamler.html#yamler.dictcopy', 'lazystudent/core.py'),
                                  'lazystudent.core.Yamler.dump': ('yamler.html#yamler.dump', 'lazystudent/core.py'),
                                  'lazystudent.core.Yamler.dumpChanged': ('yamler.html#yamler.dumpchanged', 'lazystudent/core.py'),
                                  'lazystudent.core.Yamler.ids': ('yamler.html#yamler.ids', 'lazystudent/core.py'),
                                  'lazystudent.core.Yamler.initialize': ('yamler.html#yamler.initialize', 'lazystudent/core.py'),
                                  'lazystudent.core.Yamler.remove': ('yamler.html#yamler.remove', 'lazystudent/core.py'),
                                  'lazystudent.core.Yamler.scan': ('yamler.html#yamler.scan', 'lazystudent/core.py'),
                                  'lazystudent.core.Yamler.store': ('yamler.html#yamler.store', 'lazystudent/core.py'),
                                  'lazystudent.core.Yamler.switch': ('yamler.html#yamler.switch', 'lazystudent/core.py')}}}
